const players = [
  { "number": "00", "name": "羽月 隆太郎" },
  { "number": "00", "name": "上本 崇司" },
  { "number": "02", "name": "田中 広輔" },
  { "number": "04", "name": "矢野 雅哉" },
  { "number": "05", "name": "小園 海斗" },
  { "number": "07", "name": "堂林 翔太" },
  { "number": "09", "name": "秋山 翔吾" },
  { "number": "10", "name": "佐々木 泰" },
  { "number": "12", "name": "大道 温貴" },
  { "number": "13", "name": "森浦 大輔" },
  { "number": "14", "name": "大瀬良 大地" },
  { "number": "16", "name": "森 翔平" },
  { "number": "17", "name": "常廣 羽也斗" },
  { "number": "18", "name": "森下 暢仁" },
  { "number": "19", "name": "床田 寛樹" },
  { "number": "20", "name": "栗林 良吏" },
  { "number": "21", "name": "中﨑 翔太" },
  { "number": "22", "name": "髙 太一" },
  { "number": "24", "name": "黒原 拓未" },
  { "number": "25", "name": "新井 貴浩" },
  { "number": "26", "name": "益田 武尚" },
  { "number": "27", "name": "會澤 翼" },
  { "number": "28", "name": "佐藤 柳之介" },
  { "number": "29", "name": "ケムナ 誠" },
  { "number": "30", "name": "滝田 一希" },
  { "number": "31", "name": "坂倉 将吾" },
  { "number": "32", "name": "石原 貴規" },
  { "number": "33", "name": "菊池 涼介" },
  { "number": "34", "name": "高橋 昂也" },
  { "number": "35", "name": "赤塚 健利" },
  { "number": "36", "name": "塹江 敦哉" },
  { "number": "37", "name": "野間 峻祥" },
  { "number": "38", "name": "宇草 孔基" },
  { "number": "39", "name": "長谷部 銀次" },
  { "number": "40", "name": "磯村 嘉孝" },
  { "number": "41", "name": "鈴木 健矢" },
  { "number": "42", "name": "ドミンゲス" },
  { "number": "43", "name": "島内 颯太郎" },
  { "number": "44", "name": "林 晃汰" },
  { "number": "45", "name": "松本 竜也" },
  { "number": "46", "name": "河野 佳" },
  { "number": "47", "name": "斉藤 優汰" },
  { "number": "48", "name": "アドゥワ 誠" },
  { "number": "49", "name": "渡邉 悠斗" },
  { "number": "50", "name": "中村 健人" },
  { "number": "52", "name": "末包 昇大" },
  { "number": "53", "name": "岡本 駿" },
  { "number": "54", "name": "韮澤 雄也" },
  { "number": "55", "name": "松山 竜平" },
  { "number": "56", "name": "久保 修" },
  { "number": "57", "name": "持丸 泰輝" },
  { "number": "58", "name": "仲田 侑仁" },
  { "number": "59", "name": "大盛 穂" },
  { "number": "60", "name": "田村 俊介" },
  { "number": "61", "name": "ファビアン" },
  { "number": "62", "name": "清水 叶人" },
  { "number": "63", "name": "内田 湘大" },
  { "number": "64", "name": "髙木 翔斗" },
  { "number": "65", "name": "玉村 昇悟" },
  { "number": "66", "name": "遠藤 淳志" },
  { "number": "67", "name": "菊地 ハルン" },
  { "number": "68", "name": "ハーン" },
  { "number": "69", "name": "山足 達也" },
  { "number": "70", "name": "日髙 暖己" },
  { "number": "94", "name": "佐藤 啓介" },
  { "number": "95", "name": "モンテロ" },
  { "number": "96", "name": "中村 奨成" },
  { "number": "97", "name": "中村 貴浩" },
  { "number": "99", "name": "二俣 翔一" },
  { "number": "120", "name": "杉田 健" },
  { "number": "121", "name": "名原 典彦" },
  { "number": "122", "name": "安竹 俊喜" },
  { "number": "123", "name": "小船 翼" },
  { "number": "125", "name": "辻 大雅" },
  { "number": "126", "name": "竹下 海斗" },
  { "number": "127", "name": "前川 誠太" },
  { "number": "128", "name": "杉原 望来" },
  { "number": "129", "name": "小林 樹斗" },
  { "number": "130", "name": "ラミレス" },
  { "number": "131", "name": "ロベルト" }
];
